# Search Role Definition

# Role Metadata
role:
  name: "search"
  version: "1.0.0"
  description: "Specialized role for web search, information retrieval, and content extraction"
  llm_type: "WEAK" # Search queries are straightforward and don't need complex reasoning
  author: "system@generative-agent"
  when_to_use: |
    Use this role when you need to:
    - Search the web for information using Tavily API
    - Find relevant and accurate information from multiple sources
    - Extract content from specific web pages and articles
    - Scrape websites for detailed content analysis
    - Perform filtered searches by domain, date, or content type
    - Search for news articles and academic papers
    - Summarize search results clearly with source citations
    - Research topics and gather comprehensive data

# Model Parameters
model_config:
  temperature: 0.2 # Low temperature for factual searches
  max_tokens: 2048 # Moderate token limit for search results
  max_context: 64000 # Standard context for search tasks
  top_p: 0.9 # Focused sampling

# Prompts
prompts:
  system: |
    You are a web search specialist. Your capabilities include:
    1. **Tavily Search**: Use web_search for fast, accurate web searches without scraping
    2. **Filtered Search**: Use search_with_filters for domain-specific searches
    3. **News Search**: Use search_news for current news and events
    4. **Academic Search**: Use search_academic for scholarly content
    5. **Pipeline Search**: Use search_and_scrape_pipeline when content extraction is needed
    6. **Wikipedia Search**: Use wikipedia_search_pipeline for Wikipedia content

    **Tool Selection Priority:**
    - For general information: Use web_search (fastest, most reliable)
    - For news/current events: Use search_news
    - For academic research: Use search_academic
    - For specific domains: Use search_with_filters
    - Only use pipeline tools if content extraction is specifically requested

    Always provide clear, well-structured results with source citations.

# Tool Configuration
tools:
  # Automatic tool selection via LLM
  automatic: true

  # Tavily-based search tools (primary)
  shared:
    - "web_search" # Primary Tavily search tool
    - "search_with_filters" # Filtered Tavily search
    - "search_news" # News-specific search
    - "search_academic" # Academic search
    # Pipeline tools (secondary - for content extraction)
    - "search_and_scrape_pipeline"
    - "wikipedia_search_pipeline"
    - "multi_source_search_pipeline"
    # Content extraction tools (when needed)
    - "scrape_webpage"
    - "extract_article_content"

# Basic Capabilities
capabilities:
  max_iterations: 8
  timeout_seconds: 240

# Logging Configuration
logging:
  level: "INFO"
  include_tool_calls: true
