# Calendar Role Definition - Enhanced Hybrid Pattern

# Role Metadata
role:
  name: "calendar"
  version: "2.0.0"
  description: "Calendar role with pre-processing parameter extraction and post-processing confirmation"
  fast_reply: true # Enable fast-path routing for calendar operations
  llm_type: "WEAK" # Calendar operations are straightforward
  author: "system@generative-agent"
  when_to_use: |
    Use this role when you need to:
    - Add, update, or delete calendar events with parameter extraction
    - Check availability and schedule conflicts
    - Manage recurring appointments with validation
    - Set reminders and notifications
    - Query calendar information efficiently

# Enhanced parameter schema for routing extraction
parameters:
  action:
    type: "string"
    required: true
    description: "Calendar action to perform"
    examples: ["add", "update", "delete", "get", "check_availability"]
    enum: ["add", "update", "delete", "get", "check_availability"]

  title:
    type: "string"
    required: false
    description: "Event title for add/update operations"
    examples: ["Team Meeting", "Doctor Appointment", "Lunch with Client"]

  start_time:
    type: "string"
    required: false
    description: "Event start time"
    examples: ["2024-12-25 14:30", "tomorrow 2pm", "next Monday 9am"]

  end_time:
    type: "string"
    required: false
    description: "Event end time"
    examples: ["2024-12-25 15:30", "tomorrow 3pm", "next Monday 10am"]

  event_id:
    type: "string"
    required: false
    description: "Event ID for update/delete operations"

  description:
    type: "string"
    required: false
    description: "Event description or notes"

  location:
    type: "string"
    required: false
    description: "Event location"
    examples: ["Conference Room A", "123 Main St", "Zoom"]

# Lifecycle hooks for hybrid execution
lifecycle:
  pre_processing:
    enabled: true
    functions:
      - name: "parse_calendar_parameters"
        uses_parameters:
          [
            "action",
            "title",
            "start_time",
            "end_time",
            "event_id",
            "description",
            "location",
          ]
      - name: "validate_calendar_request"
        uses_parameters: ["action", "start_time", "end_time"]
    data_injection: true

  post_processing:
    enabled: true
    functions:
      - name: "format_calendar_confirmation"
        description: "Format response for clear event confirmation"
      - name: "schedule_calendar_reminder"
        description: "Schedule reminder notifications if needed"
      - name: "audit_calendar_action"
        description: "Log calendar action for tracking"

# Model Parameters
model_config:
  temperature: 0.2 # Low temperature for accurate scheduling
  max_tokens: 1024 # Moderate token limit for calendar operations
  max_context: 16000 # Sufficient context for calendar queries
  top_p: 0.9 # Focused sampling for accurate scheduling

# Enhanced system prompt with pre-processed data
prompts:
  system: |
    You are a calendar management specialist. The calendar parameters have already been extracted
    and validated in your context as pre-processed data. Focus on interpreting
    and confirming the calendar operation rather than parsing parameters.

    Available data:
    - Action requested: {action_requested}
    - Event title: {event_title}
    - Start time: {start_time}
    - End time: {end_time}
    - Event ID: {event_id}
    - Description: {event_description}
    - Location: {event_location}
    - Validation result: {validation_result}

    Provide a clear confirmation of the calendar operation:
    - For "add": Confirm event details and schedule
    - For "update": Confirm what changes were made
    - For "delete": Confirm which event was removed
    - For "get": Summarize retrieved events clearly
    - For "check_availability": Report availability status

    Always respond in natural language as your output will be used for confirmations.

# Tool Configuration - No calendar tools needed since operations are pre-processed
tools:
  automatic: false
  shared: [] # No need for calendar tools since operations are pre-processed

# Basic Capabilities
capabilities:
  max_iterations: 3
  timeout_seconds: 60

# Logging Configuration
logging:
  level: "INFO"
  include_tool_calls: true
