# Default Role Definition

# Role Metadata
role:
  name: "default"
  version: "1.0.0"
  description: "Default general-purpose role for routing and basic tasks"
  fast_reply: false # Not a fast-reply role, used for general tasks
  llm_type: "DEFAULT" # Standard model for general-purpose tasks
  author: "system@generative-agent"
  when_to_use: |
    Use this role when:
    - No specific role is requested
    - Performing general routing decisions
    - Handling basic assistant tasks
    - As a fallback when other roles are not available

# Model Parameters
model_config:
  temperature: 0.3 # Balanced temperature for general tasks
  max_tokens: 2048 # Standard token limit
  max_context: 32000 # Standard context window
  top_p: 0.9 # Standard sampling

# Prompts
prompts:
  system: |
    You are a helpful AI assistant with general capabilities. Your role is to:
    1. Provide accurate and helpful responses to user queries
    2. Analyze requests and provide appropriate routing decisions when needed
    3. Handle general tasks that don't require specialized expertise
    4. Maintain a professional and helpful tone

    Focus on being clear, accurate, and helpful in all interactions.

# Tool Configuration
tools:
  # Disable automatic tool selection - use basic tools only
  automatic: false

  # Basic shared tools for general functionality
  shared: []

# Basic Capabilities
capabilities:
  max_iterations: 5
  timeout_seconds: 120

# Logging Configuration
logging:
  level: "INFO"
  include_tool_calls: true
