# Smart Home Role Definition

# Role Metadata
role:
  name: "smart_home"
  version: "1.0.0" 
  description: "Control smart home devices including lights, thermostat, and appliances"
  fast_reply: true  # Enable fast-path routing for smart home operations
  author: "system@generative-agent"
  when_to_use: |
    Use this role when you need to:
    - Turn lights on/off and adjust brightness
    - Set thermostat temperature
    - Control smart appliances and switches
    - Check device status and connectivity
    - Manage smart home scenes and automation

# Model Parameters
model_config:
  temperature: 0.1              # Very low temperature for precise device control
  max_tokens: 1024             # Moderate token limit for device operations
  max_context: 16000           # Sufficient context for device queries
  top_p: 0.9                   # Focused sampling for accurate control

# Prompts
prompts:
  system: |
    You are a smart home control specialist. Control home devices efficiently:
    - Turn lights on/off and adjust brightness levels
    - Set thermostat temperature with proper validation
    - Control smart appliances and switches safely
    - Check device status and report connectivity issues
    - Execute smart home scenes and automation routines
    
    Always confirm device actions and provide clear feedback about
    successful operations or any device errors that occur.

# Tool Configuration
tools:
  # Use shared smart home tools for device control
  automatic: false
  
  # Manually specified shared tools for smart home functionality
  shared:
    - "home_assistant_api"
    - "smart_lights_control"
    - "thermostat_control"
    - "device_status_check"
    - "scene_control"

# Basic Capabilities
capabilities:
  max_iterations: 3
  timeout_seconds: 45

# Logging Configuration
logging:
  level: "INFO"
  include_tool_calls: true